### ISSUE TITLE
WoT: define "Private security (meta)data"

### ISSUE THREAD

**Issue by samuelweiler** [w3cping/tracking-issues#11]
"The meaning of this term in section 8.5 and 10 is not clear. I suspect mitigation of this confusion require more than merely adding a definition - there may be some deeper issue here."

https://github.com/w3c/wot-architecture/issues/380

**Comment by mlagally** [comment]
Hi @samuelweiler,
many thanks for flagging a potential problem of the definition of private security data.

Unfortunately it is difficult for me understand your exact concerns, which part of the text causes confusion?

The intention of the text is to state: 
- private security data (such as trust chains, private keys, ...) may be managed by the WoT runtime
- private security data is not accessible to applications and handled transparently by protocol bindings
- don't ever put private security data into a TD

Do these points address your concerns? 
If you see a deeper issue, please call it out, so we can address it quickly.
