### ISSUE TITLE
Need a definition for Security and Privacy

### ISSUE THREAD

**Issue by mlagally** [w3cping/tracking-issues#12]
Dear PING colleagues,
in the WoT group we need a clear definition for Security and Privacy, 
which is widely accepted in the industry.
See the discussion in https://github.com/w3c/wot-architecture/pull/368.

We consider using the terms in 
https://www.iso.org/obp/ui/#iso:std:iso-iec:27000:ed-5:v1:en
and 
https://www.iso.org/obp/ui/#iso:std:iso-iec:29100:ed-1:v1:en, 
however if there's a W3C definition of these terms, we would like to refer those.

Can you please help us with a recommendation?

Many thanks,

Michael Lagally

**Comment by mmccool** [comment]
I'm going to go ahead and modify my PR to include and cite the ISO definitions noted above.  These don't include the level of detail mentioned in https://github.com/w3c/wot-architecture/issues/375, but are better than our previous definitions and grounded in ISO standards, so they seem like a reasonable place to start... unless, as @mlagally mentions, there are better W3C definitions we could reference.

**Comment by samuelweiler** [comment]
For most purposes, I recommend citing one or both of the below:
https://w3ctag.github.io/security-questionnaire/
https://tools.ietf.org/html/rfc6973

I don't have a succinct definition for you.
