### ISSUE TITLE
Publication Manifest and Audiobooks: Formal Review Request

### ISSUE THREAD

**Issue by wareid** [w3cping/tracking-issues#15]
Hello PING!

Thank you for visiting us during TPAC. PWG is preparing to move it's 2 documents (https://w3.org/TR/pub-manifest and https://w3.org/TR/audiobooks) to CR at the end of this month, and we were hoping to have a formal thumbs-up from PING as part of our application to move forward. 

Our completed PING questionnaire is here: https://docs.google.com/document/d/1rkVNSAfQMiS72mBzeCa9dceFEh5VsqLdzxxz0Mzvtj8/edit

Please let me know if there is anything else we need to provide to you!

Thanks,
PWG Chairs

**Comment by mteixeira-wwn** [comment]
Thanks @wareid. Per a brief chat with @snyderp, it does not seem like there are interactions between Publication Manifest, Audiobooks, and Web APIs, and similarly no change to website behaviors by either specification. Therefore, nothing that immediately raises concerns. Moving the discussion here for the record.
