### ISSUE TITLE
mathml font enumerations

### ISSUE THREAD

**Issue by samuelweiler** [w3cping/tracking-issues#168]
§ https://github.com/mathml-refresh/mathml/issues/240

**Comment by plehegar** [comment]
This seems a duplicate for https://github.com/w3cping/tracking-issues/issues/169 . Any reason to have the 2 issues?

**Comment by samuelweiler** [comment]
Unclear what happened here.   @plehegar, thank you for catching it.

**Comment by plehegar** [comment]
(repository moved)
