### ISSUE TITLE
A privacy concern of "Media Capture and Streams" (w3c/mediacapture-main#630)

### ISSUE THREAD

**Issue by NalaGinrut** [w3cping/tracking-issues#27]
The original discussion https://github.com/w3cping/tracking-issues/issues/13#issuecomment-542721994

https://github.com/w3c/mediacapture-main/issues/630

**Comment by snyderp** [comment]
@NalaGinrut it looks like the WG has closed this issue.  Was the issue satisfactorily dealt with in your mind?  If so, can i close this issue too?

**Comment by NalaGinrut** [comment]
@snyderp Although I still have deeper privacy leaking concern around the API from the perspective of programming, I haven't organized convincing reason and code snippet, so let close it. I may reopen if I found something.
