### ISSUE TITLE
WebAudio: sample rate fingerprinting

### ISSUE THREAD

**Issue by plehegar** [w3cping/tracking-issues#50]
**This is a tracker issue.** Only discuss things here if they are privacy group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/WebAudio/web-audio-api/issues/1457

**Comment by plehegar** [comment]
https://github.com/WebAudio/web-audio-api/issues/1457 was actually closed 2 days ago. Feel free to reopen here if there is still a privacy issue

**Comment by samuelweiler** [comment]
Reopening the tracker issue.  I don't find this answer satisfactory.

**Comment by samuelweiler** [comment]
The WebAudio WG closed this issue.  I suggested they reopen it or redirect the discussion elsewhere: https://lists.w3.org/Archives/Public/public-audio/2020AprJun/0025.html

**Comment by samuelweiler** [comment]
As an update, the WebAudio WG reports "No progress on CR update or privacy issues."  They also have only 2-3 people showing up for each of their meetings.  https://lists.w3.org/Archives/Public/public-audio/2020AprJun/0033.html

**Comment by samuelweiler** [comment]
issue in WG repo reopened.  removing "close?" flag here.

**Comment by cwilso** [comment]
I'm not sure what you meant by "they have only 2-3 people showing up for each of their meetings," btw.  That may have been the case for a specific meeting, it's not generally true.

Please review the suggested mitigation in https://github.com/WebAudio/web-audio-api/issues/1457#issuecomment-640767256 and confirm this is sufficient.

**Comment by samuelweiler** [comment]
> I'm not sure what you meant by "they have only 2-3 people showing up for each of their meetings," btw. That may have been the case for a specific meeting, it's not generally true.

Glad to hear.  I was looking at the minutes from recent mtgs (which I now can't find).  Perhaps the attendee lists in those were incomplete.

> Please review the suggested mitigation in [WebAudio/web-audio-api#1457 (comment)](https://github.com/WebAudio/web-audio-api/issues/1457#issuecomment-640767256) and confirm this is sufficient.

I really like it.  I want to explore part 4 a little more and make sure we're not missing anything there, but I'm generally happy.

**Comment by samuelweiler** [comment]
I'm content with the new text.
