### ISSUE TITLE
WebXR API allows 2 or 3 bits of fingerprintability through isSessionSupported (immersive-web/webxr#983)

### ISSUE THREAD

**Issue by pes10k** [w3cping/tracking-issues#52]
**This is a tracker issue.** Only discuss things here if they are privacy group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/immersive-web/webxr/issues/983

**Comment by plehegar** [comment]
@pes10k @samuelweiler . Can this issue be closed? The Group is requesting to move to CR https://github.com/w3c/transitions/issues/420 .

**Comment by pes10k** [comment]
Yep, this can be closed (it was addressed by implementing the permission)
